### ISSUE TITLE
FirstReading fails with with ContentTypeError (API Request rejected)

### ISSUE THREAD

**Issue by notz** [dreautall/stromnetzgraz#2]
On my smart meter installation the first reading request seems to fail all the time, because of my readings available since.

````
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sngraz/sngraz.py", line 107, in _query
    result = await resp.json()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://webportal.stromnetz-graz.at/api/getMeterReading')
````

My reading available since is:
````
readingsAvailableSince: 2022-04-12T12:49:00
````

If i correctly understand your code that the first reading makes following requests:

**Opt-In** 

````
{
 "meterPointId": xxx,
 "fromDate": "2022-04-12T12:49:00.000+01:00",
 "toDate": "2022-04-19T12:49:00.000+01:00",
 "interval": "QuarterHourly",
 "unitOfConsump": "KWH"
}
````

Which fails with error request rejected. If i change the time to **12:00** or **12:45** the request succeeds. 

I opted in yesterday, but had the same problem before with "Opt-Middle". But i can't reproduce the error in this case, because the requests are working:

````
{
 "meterPointId": xxx,
 "fromDate": "2022-04-12T12:49:00.000+01:00",
 "toDate": "2022-04-19T00:00:00.000+01:00",
 "interval": "Daily",
 "unitOfConsump": "KWH"
}
````

**Comment by dreautall** [comment]
Interesting! My own `readingsAvailableSince` is with `T07:43:26`, but apparently that gets generously rounded to `:45` by their own system.

Thanks for all the investigation and the fix 👍 ! it's really hard to figure stuff like this out with only a single test case (myself).
