### ISSUE TITLE
Feature Request: Home-Assistant Integration

### ISSUE THREAD

**Issue by mgorfer** [dreautall/stromnetzgraz#5]
I just discovered your client library, and it works wonderful with my user data.

I would love to have that data available in Home-Assistant, the software for home automation.
Maybe you already have a WIP of some kind of Data-Logger already in use?

If nothing like that exists yet, I would be very interested to develop something.
It looks pretty easy to add Python Scripts to the Home-Assistant.

https://www.home-assistant.io/integrations/python_script

**Comment by dreautall** [comment]
Hi, I guess you're looking for https://github.com/dreautall/ha-stromnetzgraz ;)

Available via HACS!

**Comment by mgorfer** [comment]
Wow!!! I am blown away! XD
It's working perfectly!

I would love to donate something or buy you guys a beer for this very niche development, which saved me a considerable amount of time to implement by myself. (If I even would have been able to implement it at all)

Maybe adding the Home Assistant Custom Component to this repositories README would motivate more people to use it.

**Comment by dreautall** [comment]
Thanks for the nice words!

If you really want, you can do a one-time donation via Github sponsors, but you don't have to ;)

I'll add it to the README, good suggestion!
